---
title: "Lab16Sep2024-Group11"
author: "me"
date: "2024-09-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

Use a dataset

```{r}
rm(list=ls())
library(car)
df <- Prestige
head(df)

```

How to detect univariate outliers?

```{r}
df$census <- NULL
names(df)
summary(df[,1:4])
boxplot(df[,1:4])

# Target prestige

boxplot(df$prestige) # No mild outliers and no severe outliers

# Address income

boxplot(df$income)
boxplot(df$income, horizontal=T, col = "blue")

varout <- summary(df$income); varout

iqr<- varout[5] - varout[2]; iqr
upmild <- varout[5]+1.5*iqr ; upmild
upsev <- varout[5]+3*iqr ; upsev

boxplot(df$income, horizontal=T, col = "blue")
abline(v=upmild, col="orange")
abline(v=upsev, col="red")

llmild <- which( (df$income > upmild) & ( df$income < upsev))
llmild
df[ llmild, ]

llsev <- which( df$income > upsev) ; llsev
df[ llsev, ]

Boxplot(df$income,  col = "blue")
llboxplt <- Boxplot(df$income,  col = "blue", id = list( labels=rownames(df)))
llboxplt

# Many possibilities more

boxplot(df$income, horizontal=T, col = "blue", range=3)
```

Multivariate Outliers (no missing values, then go ahead!)

```{r}
library(chemometrics)

res.mout <- Moutlier( df[,1:4],quantile=0.95)
str(res.mout)

par( mfrow=c( 1,1) )
plot( res.mout$md, res.mout$rd, main="Mahalanobis: classic vs robust",pch=19)
abline( v=res.mout$cutoff, col="red")
abline( h=res.mout$cutoff, col="red")
text(res.mout$md, res.mout$rd, labels=rownames(df), adj=-1)

llmout <- which( (res.mout$md>res.mout$cutoff) & (res.mout$rd>res.mout$cutoff)); llmout

res.mout$cutoff^2
qchisq( 0.95, 4)
```

Imputation: mice library

```{r}
library(mice)
summary(df)
res.mice <- mice(df)
summary(complete(res.mice))
```

